In [114]:
import pandas as pd
import matplotlib.pyplot as plt
import re #regular expression
import numpy as np

In [126]:
df = pd.read_csv("messy_customer_sales_data.csv") #read csv file
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10195,CUST10767,Robert Lewis,female,35.0 years,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,InDia
10196,NaN,Diane Evans,M,53.0,bangalore,2023-12-31,2025-05-07,11639.0,7.0,lisadennis@example.net,5200349941,IND
10197,CUST6315,Joshua Martinez,m,25.0,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,India
10198,CUST4812,Sarah Miller,FEMALE,55.0,NaN,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,InDia
10199,CUST6588,David Potter,female,34.0,HYDERABAD,2020-10-12,2025-06-27,35211.0,10.0,kochjonathan@example.org,1926206725,India

In [4]:
df.info() # read info

<class 'pandas.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   str
 1   Name                10200 non-null  str
 2   Gender              9174 non-null   str
 3   Age                 9249 non-null   str
 4   City                9184 non-null   str
 5   Signup_Date         10200 non-null  str
 6   Last_Purchase_Date  9188 non-null   str
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  str
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   str
dtypes: float64(2), int64(1), str(9)
memory usage: 956.4 KB

In [5]:
df.describe().round() # describes statistical summary of a numerical columns in a data frame

       Purchase_Amount  Feedback_Score  Phone_Number
count           9179.0          9177.0  1.020000e+04
mean           29090.0             5.0  4.979974e+09
std           208697.0             3.0  2.902593e+09
min             -500.0             1.0  9.208990e+05
25%            12295.0             3.0  2.449157e+09
50%            24330.0             5.0  4.988639e+09
75%            37130.0             8.0  7.510448e+09
max          9999999.0            10.0  9.994402e+09

In [6]:
df.isnull().sum()/len(df)*100

Customer_ID           10.029412
Name                   0.000000
Gender                10.058824
Age                    9.323529
City                   9.960784
Signup_Date            0.000000
Last_Purchase_Date     9.921569
Purchase_Amount       10.009804
Feedback_Score        10.029412
Email                  0.000000
Phone_Number           0.000000
Country                7.176471
dtype: float64

In [7]:
df.shape

(10200, 12)

In [8]:
df[df.duplicated].shape

(15, 12)

In [9]:
df[df.duplicated]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
2032,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India
3191,NaN,Travis Schneider,f,51.0,NaN,2025-04-20,2025-02-28,48750.0,5.0,bianca77@example.net,7623118785,India
4312,CUST8305,Stanley Cain,FEMALE,51.0,Bangalore,2023-08-14,2024-11-01,11432.0,6.0,calderonbrenda@example.org,4889366037,India
5611,CUST6288,Jonathon Kim,male,46.0,Chennai,2023-11-22,2025-03-21,3301.0,6.0,tparker@example.com,5266662560,India
5680,CUST2695,Lisa Durham,NaN,46.0,Chennai,2021-04-18,2024-10-10,6511.0,3.0,andrew34@example.com,2235480149,India
5899,CUST8841,Amanda Hill,NaN,34.0,chennai,2022-09-11,2025-03-13,42092.0,4.0,ryanriley@example.net,3466026146,India
6070,CUST10780,Emily Smith,NaN,23.0,Kolkata,2023-12-09,2024-10-28,18027.0,5.0,perezchristopher@example.com,3032282870,India
6240,CUST9745,David Morales,NaN,56.0,NaN,2023-02-18,2024-12-14,49107.0,7.0,juliaknapp@example.com,9436163110,India
6425,CUST4631,George Villa,m,26.0,Mumbai,2022-05-21,2025-06-17,NaN,8.0,davidmarquez@example.com,8869465862,India
6498,CUST1711,Stephanie Elliott,NaN,44.0,MUMBAI,2023-05-17,2025-07-12,11349.0,9.0,nfischer@example.com,3270872546,NaN
7118,CUST9380,Paul Wilson,MALE,42.0,Bangalore,2025-07-31,2025-09-21,2696.0,5.0,steven57@example.net,6835989909,India
8392,CUST1436,Ralph Anderson,female,33.0,Kolkata,2022-10-21,2025-04-24,42870.0,NaN,vcosta@example.com,3739220307,India
9155,CUST10040,Mark Taylor,NaN,43.0,Delhi,2021-04-16,2025-01-13,37793.0,6.0,tinaknapp@example.org,9898365939,India
9960,CUST6220,John Rodriguez,male,51.0,Hyderabad,2021-03-28,2025-01-22,27102.0,10.0,laurahart@example.com,7462990833,India
10140,CUST4367,Amber Kennedy,F,61.0,Bangalore,2023-11-05,2025-01-10,40711.0,8.0,kellifox@example.com,5600790669,India

In [10]:
df["Customer_ID"].value_counts()

Customer_ID
CUST6560     2
CUST7652     2
CUST6833     2
CUST6106     2
CUST8964     2
            ..
CUST6352     1
CUST6146     1
CUST10767    1
CUST6315     1
CUST4812     1
Name: count, Length: 9000, dtype: int64

In [11]:
df[df["Customer_ID"] == "CUST6560"]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
96,CUST6560,Jeremy Wallace,NaN,NaN,DELHI,2022-01-09,2025-07-10,44888.0,2.0,stricklandalison@example.net,9233537609,NaN
3517,CUST6560,Jeremy Wallace,NaN,NaN,Delhi,2022-01-09,2025-07-10,44888.0,2.0,stricklandalison@example.net,9233537609,NaN

In [12]:
for col in df.columns:
    if df[col].nunique() < 20:
        print(df[col].value_counts())
        print('-'*40)

Gender
f         1184
M         1171
m         1163
F         1157
MALE      1131
female    1128
male      1121
FEMALE    1119
Name: count, dtype: int64
----------------------------------------
City
Kolkata       820
Mumbai        812
Chennai       784
Bangalore     773
Hyderabad     770
Delhi         763
CHENNAI       404
KOLKATA       395
MUMBAI        393
hyderabad     384
bangalore     383
DELHI         378
delhi         369
BANGALORE     363
HYDERABAD     360
mumbai        352
chennai       343
kolkata       338
Name: count, dtype: int64
----------------------------------------
Feedback_Score
2.0     952
4.0     947
7.0     938
6.0     927
3.0     913
8.0     912
1.0     907
9.0     903
10.0    901
5.0     877
Name: count, dtype: int64
----------------------------------------
Country
India    7132
IND       793
india     772
InDia     771
Name: count, dtype: int64
----------------------------------------

In [127]:
df.dropna(subset=["Customer_ID"], inplace = True) # remove null values using dropna

In [14]:
df

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India
...,...,...,...,...,...,...,...,...,...,...,...,...
10194,CUST6146,Cody Thompson,f,40.0,NaN,2024-08-21,2024-10-26,35101.0,1.0,mitchellrivera@example.net,6380823112,India
10195,CUST10767,Robert Lewis,female,35.0 years,delhi,2020-12-08,2025-01-25,24167.0,9.0,barrycrane@example.net,5004696571,InDia
10197,CUST6315,Joshua Martinez,m,25.0,hyderabad,2022-02-15,2025-01-11,43832.0,2.0,kelli74@example.org,8147428496,India
10198,CUST4812,Sarah Miller,FEMALE,55.0,NaN,2021-03-16,2025-05-14,18827.0,10.0,dawn84@example.org,2987564247,InDia
10199,CUST6588,David Potter,female,34.0,HYDERABAD,2020-10-12,2025-06-27,35211.0,10.0,kochjonathan@example.org,1926206725,India

In [128]:
df.isnull().sum() # checking null values

Customer_ID             0
Name                    0
Gender                934
Age                   859
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [129]:
df["Age"].unique()# checking unique values

<StringArray>
[      '52.0', '51.0 years',       '62.0',       '40.0',       '41.0',
          nan,       '18.0', '43.0 years', '40.0 years',       '26.0',
 ...
        '-10', '60.0 years', '24.0 years', '26.0 years', '21.0 years',
 '64.0 years', '50.0 years', '68.0 years', '32.0 years', '56.0 years']
Length: 109, dtype: str

In [17]:
def extract_age(age):
    age_num = re.findall('[0-9]', str(age))
    if len(age_num) > 0:
        return age_num[0]
    else:
        return age
df['Age'].apply(lambda x : extract_age(x))

0        5
1        5
2        6
3        4
4        4
        ..
10194    4
10195    3
10197    2
10198    5
10199    3
Name: Age, Length: 9177, dtype: str

In [18]:
df.columns

Index(['Customer_ID', 'Name', 'Gender', 'Age', 'City', 'Signup_Date',
       'Last_Purchase_Date', 'Purchase_Amount', 'Feedback_Score', 'Email',
       'Phone_Number', 'Country'],
      dtype='str')

In [19]:
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                   859
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [30]:
for col in ["Gender", "Age", "City", "Purchase_Amount", "Feedback_Score", "Country"]:
    df[col].fillna(df[col].mode()[0])

In [34]:
df["Last_Purchase_Date"].ffill()
df.isnull().sum()

Customer_ID           0
Name                  0
Gender                0
Age                   0
City                  0
Signup_Date           0
Last_Purchase_Date    0
Purchase_Amount       0
Feedback_Score        0
Email                 0
Phone_Number          0
Country               0
dtype: int64

In [42]:
df["Gender"].unique

<bound method Series.unique of 0             m
1             m
2             f
3        female
4             f
          ...
10194         f
10195    female
10197         m
10198    female
10199    female
Name: Gender, Length: 9177, dtype: str>

In [51]:
df["Gender"] = df["Gender"].str.capitalize().str.strip()

In [47]:
df["Gender"] = df["Gender"].replace({'m':'male', 'f':'female'})

In [52]:
df["Gender"]

0          Male
1          Male
2        Female
3        Female
4        Female
          ...
10194    Female
10195    Female
10197      Male
10198    Female
10199    Female
Name: Gender, Length: 9177, dtype: str

In [56]:
df["City"] = df["City"].str.lower().str.strip()

In [60]:
df["City"].unique()

<StringArray>
['Kolkata', 'Hyderabad', 'Chennai', 'Bangalore', 'Mumbai', 'Delhi']
Length: 6, dtype: str

In [59]:
df["City"] = df["City"].str.capitalize().str.strip()

In [61]:
df["City"]

0          Kolkata
1          Kolkata
2        Hyderabad
3        Hyderabad
4          Chennai
           ...
10194      Kolkata
10195        Delhi
10197    Hyderabad
10198      Kolkata
10199    Hyderabad
Name: City, Length: 9177, dtype: str

In [72]:
df["Country"].unique()

<StringArray>
['India', 'india']
Length: 2, dtype: str

In [69]:
df["Country"].str.strip().str.capitalize()

0        India
1        India
2        India
3        India
4        India
         ...
10194    India
10195    India
10197    India
10198    India
10199    India
Name: Country, Length: 9177, dtype: str

In [71]:
df["Country"] = df["Country"].replace({"IND": "india", "InDia": "india"})

In [125]:
df.dtypes

Customer_ID                      str
Name                             str
Gender                           str
Age                            Int64
City                             str
Signup_Date           datetime64[us]
Last_Purchase_Date    datetime64[us]
Purchase_Amount              float64
Feedback_Score               float64
Email                            str
Phone_Number                   int64
Country                          str
dtype: object

In [87]:
df.drop_duplicates(inplace = True)

In [96]:
df[df.duplicated()].shape

(0, 12)

In [102]:
df["Customer_ID"].value_counts()

Customer_ID
CUST4371     1
CUST5957     1
CUST3754     1
CUST2934     1
CUST5683     1
            ..
CUST6352     1
CUST6146     1
CUST10767    1
CUST6315     1
CUST4812     1
Name: count, Length: 9000, dtype: int64

In [101]:
df[df["Customer_ID"] == "CUST7652"]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
126,CUST7652,Denise Flores,Female,31.0,Delhi,2020-12-22,2025-07-12,18572.0,8.0,lambertdavid@example.com,8047340035,India

In [100]:
df.drop_duplicates(subset= ["Customer_ID"], keep = "first", inplace = True)

In [103]:
df.shape

(9000, 12)

In [120]:
Age = df["Age"].astype(str).str.replace(
    " years", "", regex=False
)

Age = pd.to_numeric(Age, errors="coerce")

Age = Age.replace([np.inf, -np.inf], np.nan)

df["Age"] = df["Age"] = Age.astype("Int64")

In [123]:
df.columns

Index(['Customer_ID', 'Name', 'Gender', 'Age', 'City', 'Signup_Date',
       'Last_Purchase_Date', 'Purchase_Amount', 'Feedback_Score', 'Email',
       'Phone_Number', 'Country'],
      dtype='str')

In [124]:
df["Signup_Date"] = pd.to_datetime(df["Signup_Date"])
df["Last_Purchase_Date"] = pd.to_datetime(df["Last_Purchase_Date"])